#  Copyright (C) 2018 Curt Brune <curt@cumulusnetworks.com>
#
#  Modified with permission from Benayak Karki
#
#  SPDX-License-Identifier:     GPL-2.0

#  Usage:
#  $ docker build -f Dockerfile.buster -t debian:build-env .

FROM debian:buster

COPY sources.list.buster /etc/apt/sources.list

# Add initial development packages
RUN apt-get update && apt-get install -y \
    build-essential stgit u-boot-tools util-linux \
    gperf device-tree-compiler python-all-dev xorriso \
    autoconf automake bison flex texinfo libtool libtool-bin \
    gawk libncurses5 rsync git locales autopoint vim libncurses5-dev bc \
    dosfstools mtools pkg-config git wget help2man libexpat1 \
    libexpat1-dev fakeroot python-sphinx rst2pdf \
    libefivar-dev libnss3-tools libnss3-dev libpopt-dev \
    libssl-dev sbsigntool uuid-runtime uuid-dev cpio \
    bsdmainutils curl sudo unzip tree htop libelf-dev nano dos2unix \
    python3 python3-pip net-tools

# Create build user
RUN useradd -m -s /bin/bash build && \
        adduser build sudo && \
        echo "build:build" | chpasswd

WORKDIR /home/build

# Add /sbin and /usr/sbin to build user's path
RUN echo export PATH="/sbin:/usr/sbin:\$PATH" >> .bashrc

# Add common files, like .gitconfig
COPY home .

# Create /home/build/buildenv as a mount point for sharing files with the
# host system.
RUN mkdir buildenv

# Make sure everything in /home/build is owned by the build user
RUN chown -R build:build .

RUN pip3 install click==7.1.2 click-logging==1.0.1 cmakeast==0.0.18 PyYAML==5.3.1 jsonschema==2.6.0
# crosstool-ng requires locale en_US-UTF-8
RUN sed -i 's/^# *en_US.UTF-8/en_US.UTF-8/' /etc/locale.gen
RUN locale-gen
RUN locale -a | grep en_US
RUN update-locale LANG=en_US.UTF-8 LANGUAGE=en_US:en
RUN echo 'LC_ALL=en_US.UTF-8' | sudo tee -a /etc/default/locale
RUN . /etc/default/locale


USER build

CMD ["/bin/bash", "--login"]
